rentapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name = "rentapp"


urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path("room/<int:pk>/detail/", RoomDetailView.as_view(), name="roomDetail"),
    path("room/<int:pk>/book/", RoomBookView.as_view(), name="roombook"),

    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),

    path("customer/registration/", CustomerRegistrationView.as_view(),
         name="customerRegistration"),
    path("landLord/registration/", LandLordRegistrationView.as_view(),
         name="landLordRegistration"),
    path("client/profile/", ClientProfileView.as_view(), name="clientprofile"),
    path("book/<int:pk>/cancel/", BookCancelView.as_view(), name="bookcancel"),

    path("roomlord/home/", RoomLordHOmeView.as_view(), name="roomLordhome"),
    path("roomlord/room/", RoomLordRoomsView.as_view(), name="roomlordrooms"),
    path("roomLord/add/room/", AddRoomByRoomLordView.as_view(),
         name="addRoomByRoomLord"),
    path("roomLord/<int:pk>/update/room/",
         UpdateRoomByRoomLordView.as_view(), name="roomlordupdaterooms"),
    path("roomLord/<int:pk>/delete/room/",
         DeleteRoomByRoomLordView.as_view(), name="roomlorddeleterooms"),







]

rentproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("rentapp.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/roomlord/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body class = "container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">RoomFinder</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rentapp:roomlordrooms' %}">Rooms</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'rentapp:addRoomByRoomLord' %}">Add Room</a>
            </li>
          </ul>
          
        <strong class="text-success mr-2">  logged in as: {{request.user}}</strong>
        <a href="" class="btn btn-success">My profile</a>
        <a class = "btn btn-small btn-danger m-2" href="{% url 'rentapp:logout' %}"> Logout</a>
   
        </div>
        </nav>
       
    {% block content %}

    {% endblock %}
</body>

</html>

templates/roomlord/home.html
{% extends 'roomlord/base.html' %}
    {% block content %}
   
    {% endblock %}