rentapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name = "rentapp"


urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path("room/<int:pk>/detail/", RoomDetailView.as_view(), name="roomDetail"),
    path("room/<int:pk>/book/", RoomBookView.as_view(), name="roombook"),

    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),

    path("customer/registration/", CustomerRegistrationView.as_view(),
         name="customerRegistration"),
    path("landLord/registration/", LandLordRegistrationView.as_view(),
         name="landLordRegistration"),
    path("client/profile/", ClientProfileView.as_view(), name="clientprofile"),
    path("book/<int:pk>/cancel/", BookCancelView.as_view(), name="bookcancel"),

    path("roomlord/home/", RoomLordHOmeView.as_view(), name="roomLordhome"),
    path("roomlord/room/", RoomLordRoomsView.as_view(), name="roomlordrooms"),
    path("roomLord/add/room/", AddRoomByRoomLordView.as_view(),
         name="addRoomByRoomLord"),
    path("roomLord/<int:pk>/update/room/",
         UpdateRoomByRoomLordView.as_view(), name="roomlordupdaterooms"),
    path("roomLord/<int:pk>/delete/room/",
         DeleteRoomByRoomLordView.as_view(), name="roomlorddeleterooms"),







]

rentproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("rentapp.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/normal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body class = "container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">RoomFinder</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
          {% if request.user.is_authenticated %}
          <span class="text-success mr-2" > logged in as {{request.user}}</span>  
          <a href="{% url 'rentapp:clientprofile' %}" class="btn btn-success">My profile</a>
            <a class = "btn btn-small btn-danger m-2" href="{% url 'rentapp:logout' %}"> Logout</a>
       {% else %}

        <a class="btn  btn-small btn-success m-2" href="{% url 'rentapp:landLordRegistration' %}"> Register as RoomLord</a>
         <a class="btn btn-small  btn-success m-2" href="{% url 'rentapp:customerRegistration' %}">Register as Customer</a>
         <a class="btn btn-small btn-success m-2" href="{% url 'rentapp:login' %}">Login</a>

 
       {% endif %}
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    {% block content %}

    {% endblock %}
</body>

</html>

templates/normal/clientProfile.html
{% extends 'normal/base.html' %}
    {% block content %}
<div class="container">
    <div class = "row">
        <div class = "col-md-8">
            <h3>My profile</h3>
            <table class="table table-striped">
                <tr>
                    <th>username</th>
                    <td> {{customer.user.username}}</td>
                </tr>
                <tr>
                    <th>full_name</th>
                    <td><i>{{customer.full_name}}</i> </td>
                </tr>
                <tr>
                    <th>email</th>
                    <td>{{customer.email}}</td>
                </tr>
                <tr>
                    <th>mobile</th>
                    <td>{{customer.mobile}}</td>
                </tr>
    
            </table>

    <br><hr>
</div>
    {% endblock %}

templates/normal/customerRegistration.html
{% extends 'normal/base.html' %}
{% block content %}

    <div class="row">
		<div class="col-md-6 mx-auto">
			<h3>Customer Registration Form </h3><hr><br>
			<span id = "uname"></span><br>
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
				<button id="save_bottom">submit data</button>
			</form>
				
			
		</div>
	</div>
{% endblock %}

templates/normal/home.html
{% extends 'normal/base.html' %}
    {% block content %}

<div class="container m-4 ">
    <div class="row">
            {% for room in latestrooms %}
            <div class="card m-2" style="width: 18rem;">
                {% if room.image %}
                <img src="{{room.image.url}}" class="img-fluid" alt="Card image cap">
                {% endif %}
                <div class="card-body">
                    Room : {{room.title}}<br>
                    landlord: {{room.landlord.full_name}} <br>
                    Description: {{room.description|truncatechars:"2"}}
                    <a href="{% url 'rentapp:roomDetail' room.id %}" class="btn btn-primary">View Detail</a>
                </div>
              </div>
        {% endfor %}
    </div>
</div>
      {% endblock %}
  

templates/normal/landLordRegistration.html
{% extends 'normal/base.html' %}
{% block content %}

    <div class="row">
		<div class="col-md-6 mx-auto">
			<h3>RoomLord Registration Form </h3><hr><br>
			<span id = "uname"></span><br>
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
				<button id="save_bottom">submit data</button>
			</form>
				
			
		</div>
	</div>
{% endblock %}

templates/normal/login.html
{% extends 'normal/base.html' %}
{% block login %} active {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-4 mx-auto">
        <h3>Login to continue</h3>
        <hr>
        {% if error %}
        <li class="text-danger">{{error}}</li>
        {% endif %}
        <form method="POST">
            {% csrf_token %}

            {{form.as_p}}

            <button class=" btn btn-info">Login</button>
        </form>
    </div>
</div>




{% endblock %}

templates/normal/roomBook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Book the room</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button>Book Now</button>
        
    </form>   
</body>
</html>

templates/normal/roomDetail.html
{% extends 'normal/base.html' %}
    {% block content %}

    <div class = "row">
        <div class = "col-md-8">
            <h3>Room ~ Detail</h3>
            <table class="table table-striped">
                <tr>
                    <th>Image</th>
                    <td>       {% if room.image %}
                        Images: <img src="{{room.image.url}}" class="img-fluid" alt="Card image cap" />
                        {% endif %}</td>
                </tr>
                <tr>
                    <th>Room</th>
                    <td><i>{{room.title}}</i> </td>
                </tr>
                <tr>
                    <th>Landlord</th>
                    <td>{{room.landLord.full_name}}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>
                        {{room.description}}
                    </td>
                </tr>
    
            </table>
            {% if bookingStatus %}
            <a href="{% url 'rentapp:bookcancel' room.id %}" class="btn btn-primary">Cancel your booking </a>
            {% else  %}
            <a href="{% url 'rentapp:roombook' room.id %}" class="btn btn-primary">Book Now</a>
            {% endif %}

    <br><hr>
    {% endblock %}